
class DESCRIPTOR_TYPE:
    DEVICE = 1
    CONFIGURATION = 2
    STRING = 3
    INTERFACE = 4
    ENDPOINT = 5
    INTERFACE_POWER = 8
    OTG = 9
    DEBUG = 10
    INTERFACE_ASSOCIATION = 11
    BOS = 15
    DEVICE_CAPABILITY = 16
    SUPERSPEED_USB_ENDPOINT_COMPANION = 48
    SUPERSPEEDPLUS_ISOCHRONOUS_ENDPOINT_COMPANION = 49
